services:
  - type: web
    name: piezasyaya-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node start-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
